CREATE TABLE public.tareas (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estatus boolean NOT NULL,
    titulo text NOT NULL,
    contenido text NOT NULL,
    created_at timestamptz DEFAULT now(),
    fk_user uuid REFERENCES auth.users(id) ON DELETE CASCADE
);

